import Head from 'next/head'
import {FaFacebookF, FaLinkedinIn, FaGoogle, FaRegEnvelope} from "react-icons/fa"
import{MdLockOutline} from "react-icons/md";
import Navbar from '../components/Navbar';

export default function Home() {
  return (

    <div className= "flex flex-col items-center justify-center min-h-screen py-2 bg-gradient-to-r from-blue-400 via-red-500 to-pink-500">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
        <div className='bg-white rounded-2xl shadow-2xl flex w-2/3 max-w-4xl'>
        <div className='w-3/5 p-5'>
          <div className='text-left font-bold'>
            <span className='text-blue-500'>Menu</span>RecipeApp</div>
            <div className='py-10'>
              <h2 className='text-3xl font-bold text-blue-500 mb-2'>Sign In To Your Account</h2>
              <div className='border-2 w-32 border-blue-500 inline-block mb-2'></div>
              <div className='flex justify-center my-2'>
                <a href="#" className='border-2 rounded-full border-gray-200 p-3 mx-1'>
                <FaFacebookF/>  
                </a>
                <a href="#" className='border-2 rounded-full border-gray-200 p-3 mx-1'>
                <FaLinkedinIn/>  
                </a>
                <a href="#" className='border-2 rounded-full border-gray-200 p-3 mx-1'>
                < FaGoogle/>  
                </a>
              </div>
              <p className='text-gray-500 my-3'> or use your e-mail Account.</p>
              <div className='flex flex-col items-center '>
                <div className='bg-gray-100 w-64 p-2 flex items-center mb-3'>
                  <FaRegEnvelope className='text-gray-500 m-2'/>
                <input type="email"  name="email" placeholder= "Email" className='bg-gray-100 outline-none text-sm flex-1'/>
                </div>
                <div className='bg-gray-100 w-64 p-2 flex items-center mb-3'>
                  <MdLockOutline className='text-gray-500 m-2'/>
                <input type="password"  name="password" placeholder= "Password" className='bg-gray-100 outline-none text-sm flex-1'/>
                </div>
                <div className='flex justify-between w-64 mb-5'>
                  <label className='flex items-center text-xs'>
                    <input type="checkbox" name="remember" className='mr-1'/>
                    Remember Me
                  </label>
                  <a href="#" className='text-xs'>Forgot Password?</a>
                </div>
                <a href="#" className='border-2 border-blue text-blue-500 rounded-full px-12 py-2 inline-block font-semibold hover:bg-blue-400 hover:text-white'>Login</a>
        
              </div>
            </div>
          </div>    
          {/*Sign in Section Section  */}

       <div className='w-2/5 bg-blue-400 text-white rounded-tr-2xl rounded-br-2xl py-36 px-12'>
        <h2 className='text-3xl font-bold mb-2'>Hello, User!</h2>
        <div className='border-2 w-10 border-white inline-block mb-2'></div>
        <p className='mb-10'>Don't have an account, click on the 
        <span className='text-xl'> Register</span> button below to enjoy all the features of this Application🚀</p>
        <a href="./Register" className='border-2 border-white rounded-full px-12 py-2 inline-block font-semibold hover:bg-white hover:text-blue-400'>Register</a>
        </div>    
         {/*Sign up Section Section */}

       </div>
      </main>
    </div>
    
  )
}
